version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - primo-explore-eluna-workshop
        - quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:latest
    image: primo-explore-eluna-workshop
    environment:
      # localhost:8003/discovery/?vid=01OCUL_GUE:DEV
      PROXY_SERVER: https://ocul-qu.primo.exlibrisgroup.com:443
      VIEW: ${VIEW-01OCUL_QU-QU_DEFAULT}
      #PROXY_SERVER: https://primo.tug-libraries.on.ca:443
      #VIEW: ${VIEW-DEV}
    ports:
      - 8000
      - 8003:8003
      - 3001:3001
    volumes:
      - ./primo-explore/custom:/app/primo-explore/custom/

  create-package:
    image: primo-explore-eluna-workshop
    environment:
      PROXY_SERVER: https://primo.tug-libraries.on.ca:443
      VIEW: ${VIEW-01OCUL_QU-QU_DEFAULT}
    ports:
      - 8000
      - 8003:8003
      - 3001:3001
    command: yarn create-package
    volumes:
      - ./primo-explore/custom:/app/primo-explore/custom/
      - ./packages:/app/packages/

  cypress:
    image: primo-explore-eluna-workshop
    environment:
      PROXY_SERVER: https://primo.tug-libraries.on.ca:443
      VIEW: ${VIEW-01OCUL_QU-QU_DEFAULT}
    ports:
      - 8004:8004
      - 3002:3002
    command: yarn run cypress open
    volumes:
      - ./primo-explore/custom:/app/primo-explore/custom/
